# Generated by Django 6.0.2 on 2026-03-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField()),
                ('Fecha_ingreso', models.DateField(auto_now_add=True)),
                ('proveedor', models.CharField(blank=True, max_length=250)),
                ('imagen', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
