# Generated by Django 6.0.2 on 2026-03-12 06:50

import django.db.models.deletion
from django.db import migrations, models


def migrar_proveedores(apps, schema_editor):
    ProductoModel = apps.get_model('producto', 'ProductoModel')
    Proveedor = apps.get_model('producto', 'Proveedor')
    for producto in ProductoModel.objects.exclude(proveedor_text='').exclude(proveedor_text__isnull=True):
        proveedor, _ = Proveedor.objects.get_or_create(nombre=producto.proveedor_text.strip())
        producto.proveedor_fk = proveedor
        producto.save(update_fields=['proveedor_fk'])


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_productomodel_categoria_productomodel_inventario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('contacto', models.CharField(blank=True, max_length=250)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.RenameField(
            model_name='productomodel',
            old_name='proveedor',
            new_name='proveedor_text',
        ),
        migrations.AddField(
            model_name='productomodel',
            name='proveedor_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='producto.proveedor'),
        ),
        migrations.RunPython(migrar_proveedores, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='productomodel',
            name='proveedor_text',
        ),
        migrations.RenameField(
            model_name='productomodel',
            old_name='proveedor_fk',
            new_name='proveedor',
        ),
    ]
